# Generated by Django 3.0.8 on 2020-07-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20200726_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
